name:                tgz
version:             0.1.0.0
synopsis:            The Great Zimbabwe online (copyright Splotter Spellen)
#description:
homepage:            https://github.com/5outh/tgz#readme
license:             MIT
author:              Benjamin Kovach
maintainer:          bkovach13@gmail.com
copyright:           2018 Benjamin Kovach
category:            Game
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - containers
  - http-types
  - lens
  - linear
  - MonadRandom
  - mtl
  - persistent
  - persistent-postgresql
  - persistent-template
  - random-shuffle
  - safe
  - scotty
  - text
  - time
  - validation
  - resource-pool
  - monad-logger
  - monad-control
  - wai
  - elm-bridge
  - wai-extra
  - securemem
  - cryptonite
  - uuid
  - random
  - megaparsec

library:
  source-dirs: library

executables:
  tgz:
    dependencies:
      - tgz
    source-dirs:      src
    main:             Main.hs
  generate-elm-datatypes:
    dependencies:
      - tgz
      - elm-bridge
    source-dirs: generate-elm-datatypes
    main: Main.hs

tests:
  test:
    dependencies:
      - tgz
      - hspec
    main: Main.hs
    source-dirs: tests
